DjogjaKarya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('product/', include('product.urls')),
    path('merchant/', include('merchant.urls')),
    path('article/', include('article.urls')),
    path('auth/', include('authentication.urls')),
    path('reviews/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

product/urls.py
from django.urls import path, include
from django.contrib import admin
from product.views import show_category, show_detail, filter_category_ajax, add_product,get_product, edit_product, delete_product, get_product_id, get_form_data, add_product_flutter, edit_product_flutter, delete_product_flutter

app_name = 'product'

urlpatterns = [
    # path('', coba, name='show_category'),
    path('detail/<int:id>', show_detail, name='show_detail'),
    path('', show_category, name='show_category'),
    path('filter-kategori/', filter_category_ajax, name='filter-category-ajax'),
    path('add-product/', add_product, name='add_product'),
    path('json/', get_product, name='get_product'),
    path('edit/<int:id>/', edit_product, name='edit_product'),  # URL untuk edit produk
    path('delete/<int:id>/', delete_product, name='delete_product'),  # URL untuk delete produk
    path('product/<int:id>/', get_product_id, name='get_product_id'),
    path('get-form-data/', get_form_data, name='get_form_data'),
    path('add-product-flutter/', add_product_flutter, name='add_product_flutter'),
    path('edit-product-flutter/<int:id>/', edit_product_flutter, name='edit_product_flutter'),
    path('delete-product-flutter/<int:id>/', delete_product_flutter, name='delete_product_flutter'),
     path('admin/', admin.site.urls),
    path('reviews/api/', include('review.urls')),
]

review/urls.py
from django.urls import path
from review import views  
from review.views import get_reviews, add_review_api, delete_review_api  

app_name = 'review'

urlpatterns = [ 
    path('product/<int:product_id>/reviews/', views.review_list, name='review_list'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    path('api/reviews/', get_reviews, name='get_reviews'),
    path('api/reviews/add/', add_review_api, name='add_review_api'),
    path('product/<int:product_id>/reviews/delete/<int:review_id>/', 
         views.delete_review, name='delete_review'),
    path('api/reviews/<int:review_id>/delete/', delete_review_api, name='delete_review_api'),
]

wishlist/urls.py
from django.urls import path
from .views import show_wishlist, add_to_wishlist, remove_from_wishlist, show_wishlist_flutter, add_to_wishlist_flutter, remove_from_wishlist_flutter

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('add/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:product_id>/', remove_from_wishlist, name='remove_from_wishlist'),

    path('api/', show_wishlist_flutter, name='api_show_wishlist_flutter'),
    path('api/add/<int:product_id>/', add_to_wishlist_flutter, name='api_add_to_wishlist'),
    path('api/remove/<int:product_id>/', remove_from_wishlist_flutter, name='api_remove_from_wishlist'),
]

product/models.py
from django.db import models

# Create your models here.
class Product (models.Model):

    name = models.CharField(max_length=200)
    kategori = models.CharField(max_length=200)
    harga = models.IntegerField()
    toko = models.CharField(max_length=200)
    image = models.TextField()


class Category (models.Model):
    name = models.CharField(max_length=200)
    products = models.ForeignKey(Product, on_delete=models.CASCADE, name='products')
    is_wishlist = models.BooleanField(default=False)

product/views.py
from django.shortcuts import get_object_or_404, render, redirect
from product.models import Product, Category
from merchant.models import Store
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse, HttpResponseBadRequest
import random
from django.core import serializers
from django.shortcuts import render, get_object_or_404
from .models import Product
from wishlist.models import Wishlist  # Mengimpor Wishlist dari aplikasi wishlist
import random

from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, user_passes_test
import json
from .models import Product


from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required, user_passes_test


def is_admin(user):
    return user.is_superuser  # cek admin

@csrf_exempt
@user_passes_test(is_admin)
def get_form_data(request):

    try:
        categories = [
            'Batik', 'Kerajinan Kulit', 'Perak Kotagede', 'Kerajinan Wayang',
            'Kerajinan Kayu', 'Kerajinan Anyaman', 'Kerajinan Gerabah',
            'Kerajinan Bambu', 'Kain Tenun Lurik'
        ]
        stores = list(Store.objects.values_list('name', flat=True))
        
        return JsonResponse({
            'categories': categories,
            'stores': stores
        })
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@login_required
@user_passes_test(is_admin)
def add_product(request):
    if request.method != 'POST':
        return JsonResponse({'error': 'Method not allowed'}, status=405)
    
    try:
        required_fields = ['name', 'kategori', 'harga', 'toko', 'image']
        for field in required_fields:
            if not request.POST.get(field):
                return JsonResponse(
                    {'error': f'Field {field} is required'}, 
                    status=400
                )
        
        
        product = Product.objects.create(
            name=request.POST.get('name'),
            kategori=request.POST.get('kategori'),
            harga=request.POST.get('harga'),
            toko=request.POST.get('toko'),
            image=request.POST.get('image')
        )
        
        return JsonResponse({
            'message': 'Produk berhasil ditambahkan!',
            'product': {
                'id': product.id,
                'name': product.name,
                'kategori': product.kategori,
                'harga': product.harga,
                'toko': product.toko,
                'image': product.image
            }
        }, status=201)
        
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@user_passes_test(is_admin)  
@login_required
def edit_product(request, id):
    try:
       
        product = get_object_or_404(Product, id=id)

        if request.method == 'POST':
            name = request.POST.get('name')
            kategori = request.POST.get('kategori')
            harga = request.POST.get('harga')
            toko = request.POST.get('toko')
            image = request.FILES.get('image')  
            
            product.name = name
            product.kategori = kategori
            product.harga = harga
            product.toko = toko

            if image:
                product.image = image

            product.save()

            return JsonResponse({'message': 'Produk berhasil diperbarui!', 'product_id': product.id}, status=200)

        data = {
            'product': {
                'id': product.id,
                'name': product.name,
                'kategori': product.kategori,
                'harga': product.harga,
                'toko': product.toko,
                'image': product.image,
            },
            'categories': [
                'Batik', 'Kerajinan Kulit', 'Perak Kotagede', 'Kerajinan Wayang',
                'Kerajinan Kayu', 'Kerajinan Anyaman', 'Kerajinan Gerabah',
                'Kerajinan Bambu', 'Kain Tenun Lurik'
            ],
            'stores': list(Store.objects.values_list('name', flat=True))
        }
        return JsonResponse(data)

    except Product.DoesNotExist:
        return JsonResponse({'error': 'Produk tidak ditemukan.'}, status=404)

    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)



@csrf_exempt
@user_passes_test(is_admin) 
@login_required
@csrf_exempt
@login_required
@user_passes_test(is_admin)
def delete_product(request, id):
    try:
       
        product = get_object_or_404(Product, id=id)
        
        if request.user.is_superuser:
            product.delete()
            return JsonResponse({'message': 'Produk berhasil dihapus!'})
        else:
            return JsonResponse({'error': 'Unauthorized'}, status=403)
            
    except Product.DoesNotExist:
        return JsonResponse({'error': 'Product not found'}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

def get_product(request):

    products = Product.objects.all()

    return HttpResponse(serializers.serialize("json", products), content_type="application/json")


def get_product_id(request, id):
    try:
        product = Product.objects.get(id=id)
        product_data = {
            'id': product.id,
            'name': product.name,
            'kategori': product.kategori,
            'harga': product.harga,
            'toko': product.toko,
            'image': product.image,
        }
        return JsonResponse(product_data)
    except Product.DoesNotExist:
        return HttpResponseBadRequest('Produk tidak ditemukan!')

@login_required
def show_detail(request, id):
    selected_product = Product.objects.get(pk=id)
    kategori = selected_product.kategori
    all_products = Product.objects.filter(kategori__icontains=kategori).exclude(pk=id)

    if all_products.count() >= 3:
        similar_products = random.sample(list(all_products), 3)
    else:
        similar_products = all_products

    # Check if product is in wishlist
    in_wishlist = Wishlist.objects.filter(user=request.user, product=selected_product).exists() if request.user.is_authenticated else False

    context = {
        'product': selected_product,
        'similar_product': similar_products,
        'in_wishlist': in_wishlist,
    }

    return render(request, "detail.html", context)


def filter_category_ajax(request):
    kategori = request.GET.get('kategori', 'all')

    if kategori == 'all':
        data = {
            'kainBatik': list(Product.objects.filter(kategori__icontains="Batik").values()),
            'kerajinanKulit': list(Product.objects.filter(kategori__icontains="Kerajinan Kulit").values()),
            'kerajinanPerak': list(Product.objects.filter(kategori__icontains="Perak Kotagede").values()),
            'kerajinanWayang': list(Product.objects.filter(kategori__icontains="Kerajinan Wayang").values()),
            'kerajinanKayu': list(Product.objects.filter(kategori__icontains="Kerajinan Kayu").values()),
            'kerajinanAnyaman': list(Product.objects.filter(kategori__icontains="Kerajinan Anyaman").values()),
            'kerajinanGerabah': list(Product.objects.filter(kategori__icontains="Kerajinan Gerabah Kasongan").values()),
            'kerajinanBambu': list(Product.objects.filter(kategori__icontains="Kerajinan Bambu").values()),
            'kerajinanTenun': list(Product.objects.filter(kategori__icontains="Kain Tenun Lurik").values()),
        }
    else:
        products = Product.objects.filter(kategori__icontains=kategori)
        data = {'products': list(products.values())}

    return JsonResponse(data)


@login_required
def show_category(request):
    kategori = request.GET.get('kategori', 'all')

    if kategori == 'all':
        context = {
            'kainBatik': Product.objects.filter(kategori__icontains="Batik"),
            'kerajinanKulit': Product.objects.filter(kategori__icontains="Kerajinan Kulit"),
            'kerajinanPerak': Product.objects.filter(kategori__icontains="Perak Kotagede"),
            'kerajinanWayang': Product.objects.filter(kategori__icontains="Kerajinan Wayang"),
            'kerajinanKayu': Product.objects.filter(kategori__icontains="Kerajinan Kayu"),
            'kerajinanAnyaman': Product.objects.filter(kategori__icontains="Kerajinan Anyaman"),
            'kerajinanGerabah': Product.objects.filter(kategori__icontains="Kerajinan Gerabah Kasongan"),
            'kerajinanBambu': Product.objects.filter(kategori__icontains="Kerajinan Bambu"),
            'kerajinanTenun': Product.objects.filter(kategori__icontains="Kain Tenun Lurik"),
            'selected_kategori': 'all',  # Untuk highlight kategori aktif
        }
    else:

        products = Product.objects.filter(kategori__icontains=kategori)
        context = {
            'products': products,
            'selected_kategori': kategori,
        }

    return render(request, 'category.html', context)




@csrf_exempt
@login_required
@user_passes_test(is_admin)
def add_product_flutter(request):
   if request.method == 'POST':
       try:
           product = Product.objects.create(
               name=request.POST['name'],
               kategori=request.POST['kategori'],
               harga=int(request.POST['harga']),
               toko=request.POST['toko'],
               image=request.POST['image']
           )
           return JsonResponse({
               'status': 'success',
               'message': 'Product added successfully',
               'product_id': product.id
           })
       except Exception as e:
           return JsonResponse({
               'status': 'error',
               'message': str(e)
           }, status=500)
   return JsonResponse({'status': 'error', 'message': 'Invalid method'}, status=400)

@csrf_exempt
@login_required
@user_passes_test(is_admin)

product/templates/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
<div class="container p-8">

    <div class="mb-6">
        <a href="{% url 'product:show_category' %}?kategori={{ product.kategori|urlencode }}" 
           class="text-[#6B8273] text-lg font-semibold flex items-center gap-2 hover:underline">
            <svg xmlns="http://www.w3.org/2000/svg" 
                 class="h-5 w-5" viewBox="0 0 24 24" 
                 fill="none" stroke="currentColor" stroke-width="2" 
                 stroke-linecap="round" stroke-linejoin="round">
                <path d="M15 18l-6-6 6-6" />
            </svg>
            Product / {{ product.kategori }} / {{ product.name }} - {{ product.toko }}
        </a>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
        <!-- Gambar Produk -->
        <div class="w-full">
            <img 
                src="{{ product.image }}" 
                alt="{{ product.name }}" 
                class="rounded-xl object-cover w-full h-80"
            />
        </div>

        <!-- Detail Produk -->
        <div class="flex flex-col justify-between space-y-6">
            <div>
                <h1 class="text-4xl font-bold">{{ product.name }}</h1>
                <p class="text-xl font-bold text-[#834920] mt-2">
                    Price: Rp{{ product.harga|intcomma }}
                </p>
            </div>

            <!-- Informasi Toko -->
            <div class="border-l-4 border-[#834920] pl-4 mt-2">
                <p class="text-lg font-semibold">Available at:</p>
                <p class="text-gray-700">{{ product.toko }}</p>
            </div>

            <!-- Tombol Wishlist dan Review -->
            <div class="flex gap-4 mt-4">
                <a onclick="toggleWishlist(this)" id="wishlist-button" href="{% url 'wishlist:add_to_wishlist' product.id %}" class="focus:outline-none border-2 border-gray-400 text-gray-400 text-md font-semibold py-2 px-4 rounded-full w-1/2 flex items-center justify-center transition-transform duration-300 transform hover:scale-105">
                    <svg 
                        id="wishlist-icon" 
                        xmlns="http://www.w3.org/2000/svg" 
                        class="h-6 w-6 mr-2" 
                        viewBox="0 0 24 24" 
                        fill="currentColor">
                        <path 
                            d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
                    </svg>
                    <span>Add to Wishlist</span>   
                </a>
                
                <!-- Tombol See Reviews -->
                <a href="{% url 'review:review_list' product.id %}" 
                    class="focus:outline-none border-2 border-[#834920] text-[#834920] text-md font-semibold py-2 px-4 rounded-full w-1/2 flex items-center justify-center transition-transform duration-300 transform hover:scale-105 hover:bg-[#834920] hover:text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
                    </svg>
                    <span>See Reviews</span>
                </a>
            </div>
        </div>
    </div>

    <!-- Produk Terkait -->
    <div class="mt-10">
        <h3 class="text-2xl font-semibold mb-4">Similar Product</h3>
        <div class="overflow-x-auto whitespace-nowrap">
            <div class="inline-flex gap-4">
                {% for product in similar_product %}
                    {% include 'product_card.html' %}
                {% empty %}
                    <p class="text-center text-gray-500 w-full">Tidak ada produk terkait tersedia.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script>
    function toggleWishlist(button) {
        const svg = button.querySelector('svg');
        const buttonText = button.querySelector('span');
    
        if (buttonText.innerText.trim() === "Add to Wishlist") {
            button.innerHTML = `
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 text-red-500" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
                </svg>
                <span class="text-red-500">Added to Wishlist</span>
            `;
            button.classList.remove('border-gray-400', 'text-gray-400');
            button.classList.add('border-red-500', 'text-red-500');
        } else {
            button.innerHTML = `
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 text-gray-400" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
                </svg>
                <span class="text-gray-400">Add to Wishlist</span>
            `;
            button.classList.remove('border-red-500', 'text-red-500');
            button.classList.add('border-gray-400', 'text-gray-400');
        }
    }
</script>
    
{% endblock content %}