DjogjaKarya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('product/', include('product.urls')),
    path('merchant/', include('merchant.urls')),
    path('article/', include('article.urls')),
    path('auth/', include('authentication.urls')),
    path('reviews/', include('review.urls')),
    path('wishlist/', include('wishlist.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

merchant/urls.py
from django.urls import path
from merchant.views import store_list, add_store, edit_store, delete_store, get_stores,store_products, store_detail, create_store_flutter, edit_store_flutter, delete_store_flutter, store_products_flutter, get_user_status

app_name = 'merchant'

urlpatterns = [
    path('', store_list, name='store_list'),
    path('get-stores/', get_stores, name='get_stores'),
    path('add/', add_store, name='add_store'),
    path('edit-store/<int:id>/', edit_store, name='edit_store'),
    path('delete/<int:id>', delete_store, name='delete_store'),
    path('products/', store_products, name='store_products'),
    path('detail/<int:id>/', store_detail, name='detail'),
    path('create-flutter/', create_store_flutter, name='create_store_flutter'),
    path('edit-flutter/<int:id>/', edit_store_flutter, name='edit_store_flutter'),
    path('delete-flutter/<int:id>/', delete_store_flutter, name='delete_store_flutter'),
    path('products-flutter/', store_products_flutter, name='store_products_flutter'),
    path('get-user-status/', get_user_status, name='get-user-status'),

]

product/urls.py
from django.urls import path, include
from django.contrib import admin
from product.views import show_category, show_detail, filter_category_ajax, add_product,get_product, edit_product, delete_product, get_product_id, get_form_data, add_product_flutter, edit_product_flutter, delete_product_flutter

app_name = 'product'

urlpatterns = [
    # path('', coba, name='show_category'),
    path('detail/<int:id>', show_detail, name='show_detail'),
    path('', show_category, name='show_category'),
    path('filter-kategori/', filter_category_ajax, name='filter-category-ajax'),
    path('add-product/', add_product, name='add_product'),
    path('json/', get_product, name='get_product'),
    path('edit/<int:id>/', edit_product, name='edit_product'),  # URL untuk edit produk
    path('delete/<int:id>/', delete_product, name='delete_product'),  # URL untuk delete produk
    path('product/<int:id>/', get_product_id, name='get_product_id'),
    path('get-form-data/', get_form_data, name='get_form_data'),
    path('add-product-flutter/', add_product_flutter, name='add_product_flutter'),
    path('edit-product-flutter/<int:id>/', edit_product_flutter, name='edit_product_flutter'),
    path('delete-product-flutter/<int:id>/', delete_product_flutter, name='delete_product_flutter'),
     path('admin/', admin.site.urls),
    path('reviews/api/', include('review.urls')),
]

wishlist/urls.py
from django.urls import path
from .views import show_wishlist, add_to_wishlist, remove_from_wishlist, show_wishlist_flutter, add_to_wishlist_flutter, remove_from_wishlist_flutter

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('add/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:product_id>/', remove_from_wishlist, name='remove_from_wishlist'),

    path('api/', show_wishlist_flutter, name='api_show_wishlist_flutter'),
    path('api/add/<int:product_id>/', add_to_wishlist_flutter, name='api_add_to_wishlist'),
    path('api/remove/<int:product_id>/', remove_from_wishlist_flutter, name='api_remove_from_wishlist'),
]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}'s wishlist item: {self.product.name}"

wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Wishlist
from product.models import Product
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core import serializers


@login_required
def show_wishlist(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    context = {"wishlist": wishlist_items}
    return render(request, "wishlist.html", context)

@login_required
def add_to_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist_item, created = Wishlist.objects.get_or_create(user=request.user, product=product)
    return redirect('wishlist:show_wishlist')

@login_required
def remove_from_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    Wishlist.objects.filter(user=request.user, product=product).delete()
    return redirect('wishlist:show_wishlist')

@login_required
def show_wishlist_flutter(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    # Serialize data
    data = serializers.serialize('json', wishlist_items, use_natural_foreign_keys=True)
    # Return JSON response
    return JsonResponse({'wishlist': data}, safe=False)


@login_required
def add_to_wishlist_flutter(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist_item, created = Wishlist.objects.get_or_create(user=request.user, product=product)
    if created:
        return JsonResponse({'message': 'Item added to wishlist'}, status=201)
    else:
        return JsonResponse({'message': 'Item already in wishlist'}, status=200)


@login_required
def remove_from_wishlist_flutter(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    deleted, _ = Wishlist.objects.filter(user=request.user, product=product).delete()
    if deleted:
        return JsonResponse({'message': 'Item removed from wishlist'}, status=200)
    else:
        return JsonResponse({'message': 'Item not found in wishlist'}, status=404)

wishlist/templates/wishlist.html
{% extends "base.html" %}
{% block content %}

<div class="container mx-auto mt-20 flex flex-col items-center justify-center">
    <div class="w-full flex flex-col items-center bg-white font-inter">
        <p class="mt-12 text-4xl font-gabarito font-bold text-black">Your Wishlist</p>
        <p class="mt-2 text-gray-700">Check out your favorite products and consider purchasing them!</p>

        {% if wishlist %}
            <div class="w-full flex gap-2 flex-wrap">
                {% for item in wishlist %}
                <div class="max-w-md w-full md:w-96 lg:w-96 xl:w-96 bg-white shadow-lg rounded-lg overflow-hidden m-5 mx-auto">
                    <img src="{{ item.product.image }}" class="w-full h-72 object-cover object-center" alt="{{ item.product.name }}">
                    <div class="px-6 py-4">
                        <div class="font-bold text-xl mb-2">{{ item.product.name }}</div>
                        <p class="text-gray-700 text-base">Price: Rp {{ item.product.harga|floatformat:0 }}</p>
                        <p class="text-gray-700 text-base">Merchant: {{ item.product.toko }}</p>

                        {% if item.product.merchant %}
                            <a href="{% url 'merchant:detail' item.product.merchant.id %}" class="text-[#716969] hover:text-[#2d2e2e]">View Store</a>
                        {% else %}
                            <p class="text-red-500"></p>
                        {% endif %}
                    </div>
                    <div class="px-6 py-4 flex justify-between items-center">
                        <a href="{% url 'wishlist:remove_from_wishlist' item.product.pk %}" class="bg-red-500 hover:bg-red-700 text-white font-medium py-2 px-4 rounded-md">Remove</a>
                        <a href="{% url 'product:show_detail' item.product.pk %}" class="bg-[#716969] hover:bg-[#2d2e2e] text-white font-medium py-2 px-4 rounded-md">View Product</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="mt-12 text-3xl font-gabarito font-bold text-black">Your Wishlist is Empty 🥲</p>
            <p class="mt-2 text-gray-700">Explore products and add them to your wishlist!</p>
        {% endif %}
    </div>
</div>

{% endblock content %}